/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://pgeejk73ffcp3nqnp5xnitexhu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zh4lggzp7rfe3g577wjsdyp3o4",
    "aws_cognito_identity_pool_id": "us-east-2:ab00d839-e911-4314-a337-68d332985529",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_DKMhwJ5B6",
    "aws_user_pools_web_client_id": "29js1cr5omflq2so0u318sbdnq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifybucket1135101-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
